zuul:
  prefix: /api/v1
  routes:
    uo-auth-service:
      path: /auth/**
      servideId: UO-AUTH-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost

server:
  port: 9005

spring:
  application:
    name: uo-gateway-service

# Increase the Hystrix timeout to 60s (for all)


