zuul:
  prefix: /api/v1
  routes:
    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
    project-service:
      path: /proj-mgt/**
      serviceId: PROJECT-MGT-SERVICE
    social-service:
      path: /social/**
      serviceId: SOCIAL-SERVICE
  host:
    connect-timeout-millis: 100000000 #Added 3 more zeros
    socket-timeout-millis: 100000000 #Added 3 more zeros
#    max-total-connections: 200
#    max-per-route-connections: 20
#    time-unit: milliseconds
#    time-to-live: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 9005

spring:
  application:
    name: uo-gateway-service

uo:
  zuul:
    security:
      url-path: /api/v1/auth/login
      registration-path: /api/v1/auth/users
      h2-console-path: /api/v1/auth/h2-console/**

# Increase the Hystrix timeout to 60s (for all)
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

#ribbon:
#  eureka:
#    enabled: true
#    ReadTimeout: 20000
#    ConnectTimeout: 20000