zuul:
  prefix: /api/v1
  routes:
    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
    project-service:
      path: /proj-mgt/**
      serviceId: PROJECT-MGT-SERVICE
    social-service:
      path: /social/**
      serviceId: SOCIAL-SERVICE
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
#    max-total-connections: 200
#    max-per-route-connections: 20
#    time-unit: milliseconds
#    time-to-live: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 9005

spring:
  application:
    name: uo-gateway-service

# Increase the Hystrix timeout to 60s (for all)
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

#ribbon:
#  eureka:
#    enabled: true
#    ReadTimeout: 20000
#    ConnectTimeout: 20000